# Generates css/autumn.css from css/styles.css.
# Every colour-related declaration is copied under ":where(html.autumn-mode) ..." with
# spring colours shifted to an autumn palette. :where() adds no specificity and all
# colour declarations are copied (even unchanged ones like white), so the cascade
# stays exactly the same as in styles.css. Run again after editing styles.css:
#   python tools/make-autumn-css.py
import colorsys
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "css" / "styles.css"
OUT = ROOT / "css" / "autumn.css"

# Brand colours of streaming services stay as they are
KEEP = {"#1db954", "#ff0000", "#fc3c44", "#ff5500", "#629aa9", "#a238ff", "#e53935"}

COLOR_PROPS = ("color", "background", "background-color", "border", "border-color",
               "border-top", "border-bottom", "border-left", "border-right", "outline",
               "box-shadow", "text-shadow", "-webkit-text-fill-color", "fill", "stroke")

COLOR_RE = re.compile(r"#[0-9a-fA-F]{6}\b|#[0-9a-fA-F]{3}\b|rgba?\([^)]*\)")

EXTRA = """
/* Hand-made extras */
:root:where(.autumn-mode) { --cream: #f8f1e6; --cream-soft: #f2e7d8; }
:where(html.autumn-mode) .front { background-image: url("../images/bg-autumn.jpg"); }
:where(html.autumn-mode) .spring { background-image: url("../images/bg-autumn.jpg"); }
"""


def autumn_hsl(h, l, s):
    deg = h * 360
    if s < 0.04:
        return h, l, s
    if 50 <= deg < 185:          # greens -> gold / orange / rust
        deg = max(16, 44 - (deg - 50) * 0.4)
    elif deg >= 290 or deg < 12:  # pinks, magentas -> brick red
        deg = 6
    elif 250 <= deg < 290:        # purples -> warm brown
        deg, s = 18, s * 0.6
    else:                         # oranges, browns, blues stay
        return h, l, s
    return deg / 360, l, s


def shift_hex(value):
    v = value.lower()
    if v in KEEP:
        return value
    if len(v) == 4:
        v = "#" + "".join(c * 2 for c in v[1:])
    r, g, b = (int(v[i:i + 2], 16) / 255 for i in (1, 3, 5))
    h, l, s = autumn_hsl(*colorsys.rgb_to_hls(r, g, b))
    r, g, b = colorsys.hls_to_rgb(h, l, s)
    return "#%02x%02x%02x" % tuple(round(c * 255) for c in (r, g, b))


def shift_rgba(value):
    nums = [n.strip() for n in value[value.index("(") + 1:-1].split(",")]
    hexed = shift_hex("#%02x%02x%02x" % tuple(int(float(n)) for n in nums[:3]))
    rgb = [str(int(hexed[i:i + 2], 16)) for i in (1, 3, 5)]
    fn = value[:value.index("(")]
    return f"{fn}({', '.join(rgb + nums[3:])})"


def shift(value):
    return shift_rgba(value) if value.startswith("rgb") else shift_hex(value)


def scope(selectors):
    out = []
    for sel in selectors.split(","):
        sel = sel.strip()
        if sel.startswith(":root"):
            out.append(":root:where(.autumn-mode)" + sel[5:])
        elif sel.startswith("html"):
            out.append("html:where(.autumn-mode)" + sel[4:])
        else:
            out.append(":where(html.autumn-mode) " + sel)
    return ", ".join(out)


def rules(css):
    """Yield (at_rule_or_None, selector, body) for plain and @media-nested rules."""
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    i, n = 0, len(css)
    while i < n:
        j = css.find("{", i)
        if j < 0:
            break
        head = css[i:j].strip()
        if head.startswith("@"):
            depth, k = 1, j + 1
            while depth:
                depth += {"{": 1, "}": -1}.get(css[k], 0)
                k += 1
            if head.startswith("@media"):
                for _, sel, body in rules(css[j + 1:k - 1]):
                    yield head, sel, body
            i = k
        else:
            k = css.index("}", j)
            yield None, head, css[j + 1:k]
            i = k + 1


def main():
    blocks = {}
    for media, sel, body in rules(SRC.read_text(encoding="utf-8")):
        decls = []
        for decl in body.split(";"):
            if ":" not in decl:
                continue
            prop, val = (p.strip() for p in decl.split(":", 1))
            new = COLOR_RE.sub(lambda m: shift(m.group(0)), val)
            if new != val or prop in COLOR_PROPS:
                decls.append(f"  {prop}: {new};")
        if decls:
            blocks.setdefault(media, []).append(f"{scope(sel)} {{\n" + "\n".join(decls) + "\n}")

    parts = ["/* AUTUMN MODE - generated by tools/make-autumn-css.py, do not edit by hand */", ""]
    parts += [b + "\n" for b in blocks.pop(None, [])]
    for media, bl in blocks.items():
        inner = "\n".join("  " + line for b in bl for line in b.split("\n"))
        parts.append(f"{media} {{\n{inner}\n}}\n")
    parts.append(EXTRA.strip() + "\n")
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
